function flightData() {
}
flightData.jsononeway = [ {
	"flightId" : "G8-115",
	"airline" : "Go Air",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "9:40 AM",
	"arrTime" : "12:10 PM",
	"cost" : 4085,
	"seatsAvail" : 20
}, {
	"flightId" : "G8-117",
	"airline" : "Go Air",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "05:30 PM",
	"arrTime" : "08:10 PM",
	"cost" : 4696,
	"seatsAvail" : 31
}, {
	"flightId" : "SG-501",
	"airline" : "Spicejet",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "06:05 AM",
	"arrTime" : "08:55 AM",
	"cost" : 5664,
	"seatsAvail" : 45
}, {
	"flightId" : "6E-115",
	"airline" : "Indigo",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "08:05 AM",
	"arrTime" : "10:45 AM",
	"cost" : 5697,
	"seatsAvail" : 21
}, {
	"flightId" : "9W-7125",
	"airline" : "Jet Airways",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "09:35 AM",
	"arrTime" : "12:20 PM",
	"cost" : 7561,
	"seatsAvail" : 34
}, {
	"flightId" : "AI-506",
	"airline" : "Air India",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "09:45 AM",
	"arrTime" : "12:30 AM",
	"cost" : 10064,
	"seatsAvail" : 45
}, {
	"flightId" : "AI-403",
	"airline" : "Air India",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "04:05 PM",
	"arrTime" : "07:25 PM",
	"cost" : 5615,
	"seatsAvail" : 12
}, {
	"flightId" : "S2-4235",
	"airline" : "Jet Konnect",
	"source" : "New Delhi",
	"sourceCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "07:15 PM",
	"arrTime" : "09:55 PM",
	"cost" : 4565,
	"seatsAvail" : 54
}, {
	"flightId" : "SG-502",
	"airline" : "Spicejet",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "06:35 AM",
	"arrTime" : "09:25 AM",
	"cost" : 5665,
	"seatsAvail" : 56
}, {
	"flightId" : "G8-116",
	"airline" : "Go Air",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:20 AM",
	"arrTime" : "10:55 AM",
	"cost" : 5416,
	"seatsAvail" : 1
}, {
	"flightId" : "SG-224",
	"airline" : "Spicejet",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:50 AM",
	"arrTime" : "11:30 AM",
	"cost" : 6646,
	"seatsAvail" : 34
}, {
	"flightId" : "6E-122",
	"airline" : "Indigo",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "03:00 PM",
	"arrTime" : "05:40 PM",
	"cost" : 10356,
	"seatsAvail" : 53
}, {
	"flightId" : "G8-118",
	"airline" : "Go Air",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:15 PM",
	"arrTime" : "10:50 PM",
	"cost" : 5663,
	"seatsAvail" : 13
}, {
	"flightId" : "SG-216",
	"airline" : "Spicejet",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "09:05 PM",
	"arrTime" : "11:50 PM",
	"cost" : 4663,
	"seatsAvail" : 45
}, {
	"flightId" : "9W-7120",
	"airline" : "Jet Airways",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "05:35 PM",
	"arrTime" : "08:04 PM",
	"cost" : 7986,
	"seatsAvail" : 63
}, {
	"flightId" : "AI-505",
	"airline" : "Air India",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "10:30 AM",
	"arrTime" : "12:55 PM",
	"cost" : 8533,
	"seatsAvail" : 3
}, {
	"flightId" : "AI-503",
	"airline" : "Air India",
	"source" : "Bangalore",
	"sourceCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "04:30 PM",
	"arrTime" : "07:25 PM",
	"cost" : 6786,
	"seatsAvail" : 4
} ];

flightData.jsonreturn = [ {
	"onFlightId" : "G8-115",
	"onAirline" : "Go Air",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "09:40 AM",
	"arrTime" : "12:10 PM",
	"onSeats" : 12,
	"retFlightId" : "SG-502",
	"retAirline" : "Spicejet",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "06:35 AM",
	"retArr" : "09:25 AM",
	"cost" : 9050,
	"retSeats" : 20
}, {
	"onFlightId" : "G8-117",
	"onAirline" : "Go Air",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "05:30 PM",
	"arrTime" : "08:10 PM",
	"onSeats" : 25,
	"retFlightId" : "G8-116",
	"retAirline" : "Go Air",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "08:20 AM",
	"retArr" : "10:55 AM",
	"cost" : 12115,
	"retSeats" : 31
}, {
	"onFlightId" : "SG-501",
	"onAirline" : "Spicejet",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "06:05 AM",
	"arrTime" : "08:55 AM",
	"onSeats" : 31,
	"retFlightId" : "SG-224",
	"retAirline" : "Spicejet",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "08:50 AM",
	"retArr" : "11:30 AM",
	"cost" : 12354,
	"retSeats" : 12
}, {
	"onFlightId" : "6E-115",
	"onAirline" : "Indigo",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "08:05 AM",
	"arrTime" : "10:45 AM",
	"onSeats" : 5,
	"retFlightId" : "6E-122",
	"retAirline" : "Indigo",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "03:00 PM",
	"retArr" : "05:40 PM",
	"cost" : 10500,
	"retSeats" : 46
}, {
	"onFlightId" : "9W-7125",
	"onAirline" : "Jet Airways",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "09:35 AM",
	"arrTime" : "12:20 PM",
	"onSeats" : 8,
	"retFlightId" : "G8-118",
	"retAirline" : "Go Air",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "08:15 PM",
	"retArr" : "10:50 PM",
	"cost" : 9560,
	"retSeats" : 61
}, {
	"onFlightId" : "AI-506",
	"onAirline" : "Air India",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "09:45 AM",
	"arrTime" : "12:30 PM",
	"onSeats" : 10,
	"retFlightId" : "SG-216",
	"retAirline" : "Spicejet",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "09:05 PM",
	"retArr" : "11:50 PM",
	"cost" : 8400,
	"retSeats" : 11
}, {
	"onFlightId" : "AI-403",
	"onAirline" : "Air India",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "04:05 PM",
	"arrTime" : "07:25 PM",
	"onSeats" : 19,
	"retFlightId" : "9W-7120",
	"retAirline" : "Jet Airways",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "05:35 PM",
	"retArr" : "08:04 PM",
	"cost" : 7900,
	"retSeats" : 17
}, {
	"onFlightId" : "S2-4235",
	"onAirline" : "Jet Konnect",
	"onward" : "New Delhi",
	"onwardCode" : "DEL",
	"destination" : "Bangalore",
	"destCode" : "BLR",
	"depTime" : "07:15 PM",
	"arrTime" : "09:55 PM",
	"onSeats" : 7,
	"retFlightId" : "AI-505",
	"retAirline" : "Air India",
	"return" : "New Delhi",
	"returnCode" : "DEL",
	"retDep" : "10:30 AM",
	"retArr" : "12:55 PM",
	"cost" : 10900,
	"retSeats" : 2
}, {
	"onFlightId" : "SG-502",
	"onAirline" : "Spicejet",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "06:35 AM",
	"arrTime" : "09:25 AM",
	"onSeats" : 3,
	"retFlightId" : "G8-115",
	"retAirline" : "Go Air",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "09:40 AM",
	"retArr" : "12:10 PM",
	"cost" : 11560,
	"retSeats" : 6
}, {
	"onFlightId" : "G8-116",
	"onAirline" : "Go Air",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:20 AM",
	"arrTime" : "10:55 AM",
	"onSeats" : 40,
	"retFlightId" : "G8-117",
	"retAirline" : "Go Air",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "05:30 PM",
	"retArr" : "08:10 PM",
	"cost" : 12359,
	"retSeats" : 22
}, {
	"onFlightId" : "SG-224",
	"onAirline" : "Spicejet",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:50 AM",
	"arrTime" : "11:30 AM",
	"onSeats" : 11,
	"retFlightId" : "SG-501",
	"retAirline" : "Spicejet",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "06:05 AM",
	"retArr" : "08:55 AM",
	"cost" : 11568,
	"retSeats" : 16
}, {
	"onFlightId" : "6E-122",
	"onAirline" : "Indigo",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "03:00 PM",
	"arrTime" : "05:40 PM",
	"onSeats" : 9,
	"retFlightId" : "6E-115",
	"retAirline" : "Indigo",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "08:05 AM",
	"retArr" : "10:45 AM",
	"cost" : 10579,
	"retSeats" : 6
}, {
	"onFlightId" : "G8-118",
	"onAirline" : "Go Air",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "08:15 PM",
	"arrTime" : "10:50 PM",
	"onSeats" : 1,
	"retFlightId" : "9W-7125",
	"retAirline" : "Jet Airways",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "09:35 AM",
	"retArr" : "12:20 PM",
	"cost" : 9956,
	"retSeats" : 9
}, {
	"onFlightId" : "SG-216",
	"onAirline" : "Spicejet",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "09:05 PM",
	"arrTime" : "11:50 PM",
	"onSeats" : 2,
	"retFlightId" : "AI-506",
	"retAirline" : "Air India",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "09:45 AM",
	"retArr" : "12:30 PM",
	"cost" : 8820,
	"retSeats" : 28
}, {
	"onFlightId" : "9W-7120",
	"onAirline" : "Jet Airways",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "05:35 PM",
	"arrTime" : "08:04 PM",
	"onSeats" : 11,
	"retFlightId" : "AI-403",
	"retAirline" : "Air India",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "04:05 PM",
	"retArr" : "07:25 PM",
	"cost" : 7986,
	"retSeats" : 33
}, {
	"onFlightId" : "AI-505",
	"onAirline" : "Air India",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "10:30 AM",
	"arrTime" : "12:55 PM",
	"onSeats" : 3,
	"retFlightId" : "S2-4235",
	"retAirline" : "Jet Konnect",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "07:15 PM",
	"retArr" : "09:55 PM",
	"cost" : 8533,
	"retSeats" : 12
}, {
	"onFlightId" : "AI-503",
	"onAirline" : "Air India",
	"onward" : "Bangalore",
	"onwardCode" : "BLR",
	"destination" : "New Delhi",
	"destCode" : "DEL",
	"depTime" : "04:30 PM",
	"arrTime" : "07:25 PM",
	"onSeats" : 4,
	"retFlightId" : "S2-4236",
	"retAirline" : "Jet Konnect",
	"return" : "Bangalore",
	"returnCode" : "BLR",
	"retDep" : "08:15 PM",
	"retArr" : "10:55 PM",
	"cost" : 9956,
	"retSeats" : 4
} ];